-- Terra POS unified commerce/payment migration
-- Additive only: preserves existing Auth, tenant data, products, sales and stock.

create extension if not exists pgcrypto;

-- Product and catalog fields used by the unified product workspace/exporters.
alter table public.products_v2 add column if not exists sku text;
alter table public.products_v2 add column if not exists brand text;
alter table public.products_v2 add column if not exists product_url text;
alter table public.products_v2 add column if not exists condition text not null default 'new';
alter table public.products_v2 add column if not exists availability text not null default 'in stock';
alter table public.products_v2 add column if not exists image_urls jsonb not null default '[]'::jsonb;
create index if not exists products_v2_shop_sku_idx on public.products_v2(shop_id, sku) where sku is not null;

create table if not exists public.product_images_v2 (
  id bigint generated by default as identity primary key,
  shop_id uuid not null references public.shops(id) on delete cascade,
  product_id bigint not null references public.products_v2(id) on delete cascade,
  storage_path text not null,
  public_url text,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists product_images_v2_shop_product_idx
  on public.product_images_v2(shop_id, product_id, sort_order);

-- Shop settings keeps the legacy key/value columns but also exposes typed fields
-- for the current UI and payment configuration.
alter table public.shop_settings_v2 alter column key set default 'store_profile';
alter table public.shop_settings_v2 alter column value set default '{}'::jsonb;
alter table public.shop_settings_v2 add column if not exists shop_name text;
alter table public.shop_settings_v2 add column if not exists currency text not null default 'THB';
alter table public.shop_settings_v2 add column if not exists address text;
alter table public.shop_settings_v2 add column if not exists phone text;
alter table public.shop_settings_v2 add column if not exists promptpay_number text;
alter table public.shop_settings_v2 add column if not exists bank_name text;
alter table public.shop_settings_v2 add column if not exists bank_account_name text;
alter table public.shop_settings_v2 add column if not exists bank_account_number text;
alter table public.shop_settings_v2 add column if not exists qr_image_path text;
alter table public.shop_settings_v2 add column if not exists supported_languages text[] not null default array['th','en']::text[];

-- Payment audit fields on the existing tenant-scoped sales table.
alter table public.sales add column if not exists created_at timestamptz not null default now();
alter table public.sales add column if not exists updated_at timestamptz not null default now();
alter table public.sales add column if not exists paid_amount numeric;
alter table public.sales add column if not exists change_amount numeric;
alter table public.sales add column if not exists payment_account text;
alter table public.sales add column if not exists slip_path text;
alter table public.sales add column if not exists slip_filename text;
alter table public.sales add column if not exists slip_mime text;
alter table public.sales add column if not exists slip_size bigint;
alter table public.sales add column if not exists currency text not null default 'THB';
create index if not exists sales_shop_created_at_idx on public.sales(shop_id, created_at desc);

-- Private bucket for payment evidence. Product images remain in the existing public bucket.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-slips',
  'payment-slips',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp','application/pdf']::text[]
)
on conflict (id) do update set
  name = excluded.name,
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Product image tenant isolation.
alter table public.product_images_v2 enable row level security;
drop policy if exists product_images_select_member on public.product_images_v2;
drop policy if exists product_images_insert_staff on public.product_images_v2;
drop policy if exists product_images_update_staff on public.product_images_v2;
drop policy if exists product_images_delete_manager on public.product_images_v2;
create policy product_images_select_member on public.product_images_v2
  for select to authenticated using (public.is_shop_member(shop_id));
create policy product_images_insert_staff on public.product_images_v2
  for insert to authenticated
  with check (public.is_shop_member(shop_id, array['owner','manager','staff']));
create policy product_images_update_staff on public.product_images_v2
  for update to authenticated
  using (public.is_shop_member(shop_id, array['owner','manager','staff']))
  with check (public.is_shop_member(shop_id, array['owner','manager','staff']));
create policy product_images_delete_manager on public.product_images_v2
  for delete to authenticated
  using (public.is_shop_member(shop_id, array['owner','manager']));

-- The front-store role must be able to create and edit product records.
drop policy if exists products_insert_manager on public.products_v2;
drop policy if exists products_update_manager on public.products_v2;
create policy products_insert_staff on public.products_v2
  for insert to authenticated
  with check (public.is_shop_member(shop_id, array['owner','manager','staff']));
create policy products_update_staff on public.products_v2
  for update to authenticated
  using (public.is_shop_member(shop_id, array['owner','manager','staff']))
  with check (public.is_shop_member(shop_id, array['owner','manager','staff']));

-- Storage policies use the first path segment as the tenant UUID.
create or replace function public.shop_id_from_storage_path(path text)
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  return split_part(path, '/', 1)::uuid;
exception when invalid_text_representation then
  return null;
end;
$$;

drop policy if exists terra_payment_slips_select_member on storage.objects;
drop policy if exists terra_payment_slips_insert_member on storage.objects;
drop policy if exists terra_payment_slips_delete_manager on storage.objects;
create policy terra_payment_slips_select_member on storage.objects
  for select to authenticated
  using (
    bucket_id = 'payment-slips'
    and public.shop_id_from_storage_path(name) is not null
    and public.is_shop_member(public.shop_id_from_storage_path(name))
  );
create policy terra_payment_slips_insert_member on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'payment-slips'
    and public.shop_id_from_storage_path(name) is not null
    and public.is_shop_member(public.shop_id_from_storage_path(name), array['owner','manager','staff'])
  );
create policy terra_payment_slips_delete_manager on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'payment-slips'
    and public.shop_id_from_storage_path(name) is not null
    and public.is_shop_member(public.shop_id_from_storage_path(name), array['owner','manager'])
  );

-- Atomic tenant-aware sale completion with payment evidence and editable paid total.
create or replace function public.complete_sale_with_payment(
  p_shop_id uuid,
  p_sale_number text,
  p_total numeric,
  p_payment_method text,
  p_employee_name text,
  p_items jsonb,
  p_paid_amount numeric default null,
  p_change_amount numeric default null,
  p_payment_account text default null,
  p_slip_path text default null,
  p_slip_filename text default null,
  p_slip_mime text default null,
  p_slip_size bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_sale_id bigint;
  item jsonb;
  product_row record;
  item_product_id bigint;
  item_quantity integer;
  item_price numeric;
  expected_change numeric;
begin
  if not public.is_shop_member(p_shop_id, array['owner', 'manager', 'staff']) then
    raise exception 'not_authorized';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_cart';
  end if;
  if p_total is null or p_total < 0 then
    raise exception 'invalid_total';
  end if;
  if p_paid_amount is null or p_paid_amount < p_total then
    raise exception 'invalid_paid_amount';
  end if;
  expected_change := round((p_paid_amount - p_total)::numeric, 2);
  if p_change_amount is null or p_change_amount < 0 or round(p_change_amount::numeric, 2) <> expected_change then
    raise exception 'invalid_change_amount';
  end if;
  if p_payment_method not in ('cash', 'qr', 'bank_transfer') then
    raise exception 'invalid_payment_method';
  end if;
  if p_slip_path is null or btrim(p_slip_path) = '' then
    raise exception 'slip_required';
  end if;
  if split_part(p_slip_path, '/', 1) <> p_shop_id::text then
    raise exception 'invalid_slip_path';
  end if;
  if not exists (
    select 1 from storage.objects so
    where so.bucket_id = 'payment-slips' and so.name = p_slip_path
  ) then
    raise exception 'slip_not_found';
  end if;

  insert into public.sales (
    shop_id, sale_number, total, payment_method, employee_name, status,
    paid_amount, change_amount, payment_account, slip_path, slip_filename,
    slip_mime, slip_size, currency, created_at, updated_at
  ) values (
    p_shop_id, p_sale_number, p_total, p_payment_method, p_employee_name, 'completed',
    p_paid_amount, p_change_amount, p_payment_account, p_slip_path, p_slip_filename,
    p_slip_mime, p_slip_size, 'THB', now(), now()
  ) returning id into new_sale_id;

  for item in select value from jsonb_array_elements(p_items) loop
    item_product_id := (item ->> 'product_id')::bigint;
    item_quantity := (item ->> 'quantity')::integer;
    item_price := (item ->> 'price')::numeric;
    if item_quantity is null or item_quantity <= 0 or item_price is null or item_price < 0 then
      raise exception 'invalid_item';
    end if;

    select id, stock into product_row
    from public.products_v2
    where id = item_product_id and shop_id = p_shop_id
    for update;
    if not found then
      raise exception 'product_not_found';
    end if;
    if coalesce(product_row.stock, 0) < item_quantity then
      raise exception 'insufficient_stock';
    end if;

    insert into public.sale_items_v2 (shop_id, sale_id, product_id, quantity, price)
    values (p_shop_id, new_sale_id, item_product_id, item_quantity, item_price);
    update public.products_v2
    set stock = stock - item_quantity, updated_at = now()
    where id = item_product_id and shop_id = p_shop_id;
    insert into public.stock_entries_v2 (shop_id, product_id, quantity, type, note)
    values (p_shop_id, item_product_id, -item_quantity, 'out', 'sale ' || p_sale_number);
  end loop;

  return jsonb_build_object('id', new_sale_id, 'sale_number', p_sale_number, 'paid_amount', p_paid_amount, 'change_amount', p_change_amount, 'slip_path', p_slip_path);
end;
$$;

grant execute on function public.complete_sale_with_payment(uuid, text, numeric, text, text, jsonb, numeric, numeric, text, text, text, text, bigint) to authenticated;

grant select on public.product_images_v2 to authenticated;
grant insert, update, delete on public.product_images_v2 to authenticated;
grant select on public.sales to authenticated;
